### ISSUE TITLE
Crash when entering buffer with opened channel with many users

### ISSUE THREAD

**Issue by petvoigt** [ubergeek42/weechat-android#187]
When entering buffer with opened channel which has many users like #debian or #ubuntu weechat-android crashes immediately.
Hardware: Samsung S3, operating system: CM11M12

**Comment by petvoigt** [comment]
Today I've accidentally found out that these crashes obviously are happening only if weechat is using behind my ZNC server.

**Comment by petvoigt** [comment]
Hhm, I have just run a series of test with and without ZNC again. Now everytime I enter large channels like #debian or #ubuntu weechat app crashes regardless if using ZNC or not.

**Comment by mhoran** [comment]
Hey @petvoigt. I've been unable to reproduce this myself, running the latest dev build on a Nexus 5 and Android 5.0.1. It's quite possible that there's a race somewhere in the nicklist processing code. If you find a way to reproduce this, let me know. Otherwise, I'll keep an eye on #debian to see if it happens on my device.

**Comment by petvoigt** [comment]
@mhoran: Thanks for checking this. I can confirm weechat-android crashing in a very reproducible manner when opening buffers of either #debian or #ubuntu. All other channels do not show this issue. CM11M12 is based on Android 4.4.4. My WeeChat is version 1.1.1 under Linux.

**Comment by mhoran** [comment]
Unfortunately I still have been unable to reproduce this issue. If you're able to grab a trace from the crash that would be extremely useful. Also, perhaps you could upload a crash report if you're using the Play Store version. @ubergeek42 would have to get the trace from that for us, if so.

Otherwise, you can use `adb logcat` to grab the trace and we can work with that.

**Comment by petvoigt** [comment]
@mhoran, yes, I am using the Play Store version. I would really like to help debugging this. I have just sent a report titled "trace for issue #187".

**Comment by ubergeek42** [comment]
Here's the trace from the play store for that report. Sadly doesn't look too terribly helpful :/

```
java.lang.IndexOutOfBoundsException: Not enough data
at com.ubergeek42.a.a.c.b.c(Unknown Source)
at com.ubergeek42.a.a.f.<init>(Unknown Source)
at com.ubergeek42.a.a.d.run(Unknown Source)
at java.lang.Thread.run(Thread.java:841)
```

**Comment by ubergeek42** [comment]
@petvoigt If you want to try the latest build from master, please see the new instructions on joining the beta testers group in the readme
https://github.com/ubergeek42/weechat-android/blob/master/Readme.md#google-play-beta-version

If you do that and send another crash report I think we'll have the information to hunt it down.

**Comment by petvoigt** [comment]
A few day ago I have re-organized my IRC infrastructure: I moved switched off my FreeBSD hosted ZNC server and moved WeeChat from my Linux client to my FreeBSD server. I am now connecting via tmux and WeeChat App to WeeChat on FreeBSD. Now I have no more crashed, regardless which channel I enter.

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
