### ISSUE TITLE
Crash when switching buffers

### ISSUE THREAD

**Issue by Edholm** [ubergeek42/weechat-android#229]
The development version crashes for me when switching to some buffers, but not others. I haven't discerned a pattern which buffers work and which do not. Most buffers work though...

Phone: Nexus 6 with Android 6.0 Preview 3 (Though I noticed the same problem on Android 5)

This is what logcat says about it:

```
09-24 13:33:23.497  1871  4185 E SQLiteDatabase: Error inserting context_name=6 end_time=1443094403466 context_family=1 module_id=com.google.android.contextmanager.module.DetectedActivityProducer version=1 sync_state_mod_time_millis=1443094403492 start_time=1443094394979 sync_state=0 context_id=ebd4438d-3eee-4de2-b582-49b2dfd294c9 time_type=3 proto_blob=[B@698aa0a
09-24 13:33:23.497  1871  4185 E SQLiteDatabase: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: context.context_id (code 2067)
09-24 13:33:23.497  1871  4185 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
09-24 13:33:23.497  1871  4185 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:780)
09-24 13:33:23.497  1871  4185 E SQLiteDatabase: 	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
09-24 13:33:23.497  1871  4185 E SQLiteDatabase: 	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
09-24 13:33:23.497  1871  4185 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1471)
09-24 13:33:23.497  1871  4185 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1341)
09-24 13:33:23.497  1871  4185 E SQLiteDatabase: 	at com.google.android.contextmanager.q.al.a(SourceFile:408)
09-24 13:33:23.497  1871  4185 E SQLiteDatabase: 	at com.google.android.contextmanager.q.al.b(SourceFile:383)
09-24 13:33:23.497  1871  4185 E SQLiteDatabase: 	at com.google.android.contextmanager.q.al.a(SourceFile:349)
09-24 13:33:23.497  1871  4185 E SQLiteDatabase: 	at com.google.android.contextmanager.q.al.b(SourceFile:376)
09-24 13:33:23.497  1871  4185 E SQLiteDatabase: 	at com.google.android.contextmanager.g.a.j.a(SourceFile:58)
09-24 13:33:23.497  1871  4185 E SQLiteDatabase: 	at com.google.android.contextmanager.g.a.a.run(SourceFile:52)
09-24 13:33:23.497  1871  4185 E SQLiteDatabase: 	at com.google.android.contextmanager.g.i.handleMessage(SourceFile:215)
09-24 13:33:23.497  1871  4185 E SQLiteDatabase: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-24 13:33:23.497  1871  4185 E SQLiteDatabase: 	at android.os.Looper.loop(Looper.java:148)
09-24 13:33:23.497  1871  4185 E SQLiteDatabase: 	at android.os.HandlerThread.run(HandlerThread.java:61)
09-24 13:33:23.518   382  1290 D audio_hw_primary: out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
09-24 13:33:23.522  2109  2109 I Keyboard.Facilitator: onFinishInput()
09-24 13:33:23.578  1871  4185 E SQLiteDatabase: Error inserting context_name=6 end_time=1443094403552 context_family=1 module_id=com.google.android.contextmanager.module.DetectedActivityProducer version=1 sync_state_mod_time_millis=1443094403576 start_time=1443094403466 sync_state=0 context_id=c21935cf-911f-4471-8d18-d510f65cebae time_type=3 proto_blob=[B@d17d898
09-24 13:33:23.578  1871  4185 E SQLiteDatabase: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: context.context_id (code 2067)
09-24 13:33:23.578  1871  4185 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
09-24 13:33:23.578  1871  4185 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:780)
09-24 13:33:23.578  1871  4185 E SQLiteDatabase: 	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
09-24 13:33:23.578  1871  4185 E SQLiteDatabase: 	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
09-24 13:33:23.578  1871  4185 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1471)
09-24 13:33:23.578  1871  4185 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1341)
09-24 13:33:23.578  1871  4185 E SQLiteDatabase: 	at com.google.android.contextmanager.q.al.a(SourceFile:408)
09-24 13:33:23.578  1871  4185 E SQLiteDatabase: 	at com.google.android.contextmanager.q.al.b(SourceFile:383)
09-24 13:33:23.578  1871  4185 E SQLiteDatabase: 	at com.google.android.contextmanager.q.al.a(SourceFile:349)
09-24 13:33:23.578  1871  4185 E SQLiteDatabase: 	at com.google.android.contextmanager.q.al.b(SourceFile:376)
09-24 13:33:23.578  1871  4185 E SQLiteDatabase: 	at com.google.android.contextmanager.g.a.j.a(SourceFile:58)
09-24 13:33:23.578  1871  4185 E SQLiteDatabase: 	at com.google.android.contextmanager.g.a.a.run(SourceFile:52)
09-24 13:33:23.578  1871  4185 E SQLiteDatabase: 	at com.google.android.contextmanager.g.i.handleMessage(SourceFile:215)
09-24 13:33:23.578  1871  4185 E SQLiteDatabase: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-24 13:33:23.578  1871  4185 E SQLiteDatabase: 	at android.os.Looper.loop(Looper.java:148)
09-24 13:33:23.578  1871  4185 E SQLiteDatabase: 	at android.os.HandlerThread.run(HandlerThread.java:61)
09-24 13:33:23.594  2109  2109 I Keyboard.Facilitator: onFinishInput()
09-24 13:33:23.597 27579 27599 E AndroidRuntime: FATAL EXCEPTION: Thread-1758
09-24 13:33:23.597 27579 27599 E AndroidRuntime: Process: com.ubergeek42.WeechatAndroid.dev, PID: 27579
09-24 13:33:23.597 27579 27599 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=256; index=99999
09-24 13:33:23.597 27579 27599 E AndroidRuntime: 	at com.ubergeek42.a.c.a(Unknown Source)
09-24 13:33:23.597 27579 27599 E AndroidRuntime: 	at com.ubergeek42.a.a.b(Unknown Source)
09-24 13:33:23.597 27579 27599 E AndroidRuntime: 	at com.ubergeek42.a.a.b(Unknown Source)
09-24 13:33:23.597 27579 27599 E AndroidRuntime: 	at com.ubergeek42.a.a.a(Unknown Source)
09-24 13:33:23.597 27579 27599 E AndroidRuntime: 	at com.ubergeek42.WeechatAndroid.service.d.a(Unknown Source)
09-24 13:33:23.597 27579 27599 E AndroidRuntime: 	at com.ubergeek42.WeechatAndroid.service.a.a(Unknown Source)
09-24 13:33:23.597 27579 27599 E AndroidRuntime: 	at com.ubergeek42.WeechatAndroid.service.m.a(Unknown Source)
09-24 13:33:23.597 27579 27599 E AndroidRuntime: 	at com.ubergeek42.a.a.b.a(Unknown Source)
09-24 13:33:23.597 27579 27599 E AndroidRuntime: 	at com.ubergeek42.a.a.d.run(Unknown Source)
09-24 13:33:23.597 27579 27599 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
09-24 13:33:23.598   983  4733 W ActivityManager:   Force finishing activity com.ubergeek42.WeechatAndroid.dev/com.ubergeek42.WeechatAndroid.WeechatActivity
```

Thoughts?

**Comment by oakkitten** [comment]
what is the build id? the one from the about dialogue

**Comment by Edholm** [comment]
@oakkitten I'm currently using v0.10-47-gb58eefc but have noticed it since color themes were added. (I just downgraded and haven't tried since)

**Comment by oakkitten** [comment]
i wanted build id to deobfuscate the calls. as you might have guessed "com.ubergeek42.a.c.a" is not really how the method is called.. apparently proguard is more or less consistent in its obfuscation, but i still couldn't get the right method calls—probably because the builds are made by travis and it can generate mappings different from what i see. windows here.

anyways, you'd be able to get the correct method calls if you ran a debug version but you'd need to install android studio for that. alternatively @ubergeek42 might get traceback deobfuscated.. or other devs might have any clues

we need to get rid of the stupid obfuscation, really, it's only there because proguard is somehow not working without it

**Comment by Edholm** [comment]
@oakkitten this is the unobfuscated stack trace

```
10-06 12:59:15.054  13062-13062/com.ubergeek42.WeechatAndroid.debug I/MainPagerAdapter﹕ openBuffer(irc.znc-digit(SSL).#digIT13, focus=true)
10-06 12:59:15.285  13062-13225/com.ubergeek42.WeechatAndroid.debug E/AndroidRuntime﹕ FATAL EXCEPTION: Thread-644
    Process: com.ubergeek42.WeechatAndroid.debug, PID: 13062
    java.lang.ArrayIndexOutOfBoundsException: length=256; index=99999
            at com.ubergeek42.weechat.ColorScheme.getColor(ColorScheme.java:213)
            at com.ubergeek42.weechat.Color.getColorExtended(Color.java:268)
            at com.ubergeek42.weechat.Color.setColor(Color.java:253)
            at com.ubergeek42.weechat.Color.parseColors(Color.java:377)
            at com.ubergeek42.weechat.Color.parse(Color.java:136)
            at com.ubergeek42.WeechatAndroid.service.Buffer$Line.processMessage(Buffer.java:615)
            at com.ubergeek42.WeechatAndroid.service.Buffer.addLine(Buffer.java:229)
            at com.ubergeek42.WeechatAndroid.service.BufferList$6.handleMessage(BufferList.java:503)
            at com.ubergeek42.weechat.relay.RelayConnection.handleMessage(RelayConnection.java:263)
            at com.ubergeek42.weechat.relay.RelayConnection.access$000(RelayConnection.java:38)
            at com.ubergeek42.weechat.relay.RelayConnection$2.run(RelayConnection.java:199)
            at java.lang.Thread.run(Thread.java:818)
```

**Comment by oakkitten** [comment]
please tell me if this doesn't fix it or results in something else :/

**Comment by Edholm** [comment]
Nice! It works!
