### ISSUE TITLE
Crash during/after Connection

### ISSUE THREAD

**Issue by genofire** [ubergeek42/weechat-android#312]
Version: v0.12-git (from F-Droid)

Popup:

`"weechat" was closed`

Logcat:
```
E/AndroidRuntime(17033): Process: com.ubergeek42.WeechatAndroid, PID: 17033
E/AndroidRuntime(17033): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
E/AndroidRuntime(17033): 	at com.ubergeek42.weechat.relay.protocol.Data.getHdata(Data.java:173)
E/AndroidRuntime(17033): 	at com.ubergeek42.weechat.relay.protocol.Data.getObject(Data.java:273)
E/AndroidRuntime(17033): 	at com.ubergeek42.weechat.relay.RelayMessage.<init>(RelayMessage.java:2238)
E/AndroidRuntime(17033): 	at com.ubergeek42.weechat.relay.connection.AbstractConnection.access$300(AbstractConnection.java:2147)
E/AndroidRuntime(17033): 	at com.ubergeek42.weechat.relay.connection.AbstractConnection$2.run(AbstractConnection.java:83)
E/AndroidRuntime(17033): 	at java.lang.Thread.run(Thread.java:818)
```

Weechat: 
```
                      │1910  weechat            ? relay: new client on port 8001: 5/weechat/IPv4-Adress
                      │1910  weechat        =!= ? relay: reading data on socket for client 5/weechat/91.58.254.249: error 104 (connection closed by peer)
                      │1910  weechat            ? relay: disconnected from client 5/weechat/IPv4-Adress

```

I have try, Weechat SSL and Plain Authentification -> (Connection by https://www.glowing-bear.org/# works well)

**Comment by oakkitten** [comment]
try current master, this should have been fixed

**Comment by genofire** [comment]
Exists a build anywhere?
I hate to build android applications?

**Comment by ubergeek42** [comment]
http://weechat-android.ubergeek42.com contains automatic builds for every
commit. You can always get the latest nightly there.

**Comment by genofire** [comment]
Ui, thats what i am searching for -> sry for this issue
