### ISSUE TITLE
Crash when setting button text in BufferFragment

### ISSUE THREAD

**Issue by oakkitten** [ubergeek42/weechat-android#354]
happens on 1f407ca ([line](https://github.com/ubergeek42/weechat-android/blob/1f407caa24899a89d6d5d32460b0b47f442f90a4/weechat-android/src/main/java/com/ubergeek42/WeechatAndroid/fragments/BufferFragment.java#L315))

> 2 Crashes from android 6, 2 on android 7. Oldest crash is from Nov 2016. All on the same hardware, Galaxy S7.

    java.lang.IllegalStateException: Fragment BF [irc.foo.bar] not attached to Activity
        at android.support.v4.app.Fragment.getResources(Fragment.java:642)
        at android.support.v4.app.Fragment.getString(Fragment.java:664)
        at com.ubergeek42.WeechatAndroid.fragments.BufferFragment$3.run(BufferFragment.java:315)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6688)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by Zopieux** [comment]
http://stackoverflow.com/q/10919240/180709

Seems like we should get resources from somewhere else, I guess the `activity` object could work.
