### ISSUE TITLE
Crash outside app code in InputConnection.closeConnection() when switching theme (recreating activity)

### ISSUE THREAD

**Issue by oakkitten** [ubergeek42/weechat-android#406]
2018-10-25 16:43:20.681 20592-20592/com.ubergeek42.WeechatAndroid.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ubergeek42.WeechatAndroid.debug, PID: 20592
    java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.inputmethod.InputConnection.closeConnection()' on a null object reference
        at android.view.inputmethod.InputConnectionWrapper.closeConnection(InputConnectionWrapper.java:270)
        at com.android.tools.profiler.support.event.InputConnectionWrapper.closeConnection(InputConnectionWrapper.java:49)
        at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:541)
        at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:85)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6501)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by oakkitten** [comment]
this is probably resolved
