### ISSUE TITLE
0.13 crash

### ISSUE THREAD

**Issue by killerrabbit** [ubergeek42/weechat-android#432]
Version 0.13 crashes randomly. I've been unable to determine any particular thing that causes it to crash. Sometimes it crashes while actively using it, or while in the background. Below is the backtrace and output from weechat's raw relay buffer around that time.

Weechat version: 2.5
Weechat-Android version: 0.13, f-droid build

```
03-14 16:06:25.533 24926 24946 E AndroidRuntime: FATAL EXCEPTION: r0
03-14 16:06:25.533 24926 24946 E AndroidRuntime: Process: com.ubergeek42.WeechatAndroid, PID: 24926
03-14 16:06:25.533 24926 24946 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference
03-14 16:06:25.533 24926 24946 E AndroidRuntime:        at com.ubergeek42.WeechatAndroid.relay.BufferList$4.handleMessage(BufferList.java:431)
03-14 16:06:25.533 24926 24946 E AndroidRuntime:        at com.ubergeek42.WeechatAndroid.relay.BufferList.handleMessage(BufferList.java:102)
03-14 16:06:25.533 24926 24946 E AndroidRuntime:        at com.ubergeek42.WeechatAndroid.service.RelayService.onMessage(RelayService.java:318)
03-14 16:06:25.533 24926 24946 E AndroidRuntime:        at com.ubergeek42.weechat.relay.RelayConnection.onMessage(RelayConnection.java:93)
03-14 16:06:25.533 24926 24946 E AndroidRuntime:        at com.ubergeek42.weechat.relay.connection.AbstractConnection.access$300(AbstractConnection.java:2147)
03-14 16:06:25.533 24926 24946 E AndroidRuntime:        at com.ubergeek42.weechat.relay.connection.AbstractConnection$2.run(AbstractConnection.java:83)
03-14 16:06:25.533 24926 24946 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:764)
```

```
14:13:06:19 <-- [1] weechat obj: 244/371 bytes (35%, 0.03ms), id: _buffer_localvar_changed
14:13:06:19 <-- [1] weechat obj: 246/368 bytes (34%, 0.03ms), id: _buffer_localvar_changed
14:13:06:19 <-- [1] weechat obj: 235/372 bytes (37%, 0.03ms), id: _buffer_localvar_changed
14:13:06:19 <-- [1] weechat obj: 231/363 bytes (37%, 0.03ms), id: _buffer_localvar_changed
14:13:06:19 <-- [1] weechat obj: 251/384 bytes (35%, 0.03ms), id: _buffer_localvar_changed
14:13:06:19 <-- [1] weechat obj: 250/375 bytes (34%, 0.03ms), id: _buffer_localvar_changed
14:13:06:19 <-- [1] weechat obj: 236/372 bytes (37%, 0.04ms), id: _buffer_localvar_changed
14:13:06:19 <-- [1] weechat obj: 254/383 bytes (34%, 0.04ms), id: _buffer_localvar_changed
14:13:06:19 <-- [1] weechat obj: 247/368 bytes (33%, 0.07ms), id: _buffer_localvar_changed
14:13:06:19 <-- [1] weechat obj: 252/384 bytes (35%, 0.05ms), id: _buffer_localvar_changed
14:13:06:20 <-- [1] weechat obj: 251/375 bytes (34%, 0.06ms), id: _buffer_localvar_changed
14:13:06:20 <-- [1] weechat obj: 233/363 bytes (36%, 0.05ms), id: _buffer_localvar_changed
14:13:06:20 <-- [1] weechat obj: 245/371 bytes (34%, 0.06ms), id: _buffer_localvar_changed
14:13:06:21 <-- [1] weechat obj: 300/409 bytes (27%, 0.06ms), id: _buffer_line_added
14:13:06:21 <-- [1] weechat obj: 232/363 bytes (37%, 0.05ms), id: _buffer_localvar_changed
14:13:06:21 <-- [1] weechat obj: 233/363 bytes (36%, 0.05ms), id: _buffer_localvar_changed
14:13:06:22 <-- [1] weechat obj: 251/368 bytes (32%, 0.05ms), id: _buffer_localvar_changed
14:13:06:22 <-- [1] weechat obj: 268/393 bytes (32%, 0.04ms), id: _buffer_localvar_changed
14:13:06:22 <-- [1] weechat obj: 252/368 bytes (32%, 0.06ms), id: _buffer_localvar_changed
14:13:06:23 <-- [1] weechat obj: 269/393 bytes (32%, 0.05ms), id: _buffer_localvar_changed
14:13:06:23 <-- [1] weechat obj: 262/394 bytes (34%, 0.05ms), id: _buffer_localvar_changed
14:13:06:23 <-- [1] weechat obj: 242/380 bytes (37%, 0.03ms), id: _buffer_localvar_changed
14:13:06:24 <-- [1] weechat obj: 262/394 bytes (34%, 0.05ms), id: _buffer_localvar_changed
14:13:06:24 --> [1] weechat (last_read_lines) hdata buffer:gui_buffers(*)/own_lines/last_read_line/data buffer
14:13:06:24 <-- [1] weechat obj: 950/3066 bytes (70%, 0.17ms), id: last_read_lines
14:13:06:24 <-- [1] weechat obj: 188/245 bytes (24%, 0.04ms), id: _buffer_line_added
14:13:06:24 --> [1] weechat (hotlist) hdata hotlist:gui_hotlist(*) buffer,count
14:13:06:24 <-- [1] weechat obj: 157/303 bytes (49%, 0.04ms), id: hotlist
14:13:06:24 <-- [1] weechat obj: 160/241 bytes (34%, 0.05ms), id: _nicklist
14:13:06:24 <-- [1] weechat obj: 266/397 bytes (33%, 0.05ms), id: _buffer_localvar_changed
14:13:06:24 <-- [1] weechat obj: 242/372 bytes (35%, 0.03ms), id: _buffer_localvar_changed
14:13:06:24 <-- [1] weechat obj: 237/346 bytes (32%, 0.03ms), id: _buffer_localvar_changed
14:13:06:24 <-- [1] weechat obj: 266/397 bytes (33%, 0.05ms), id: _buffer_localvar_changed
14:13:06:24 <-- [1] weechat obj: 242/372 bytes (35%, 0.05ms), id: _buffer_localvar_changed
14:13:06:24 <-- [1] weechat obj: 237/346 bytes (32%, 0.03ms), id: _buffer_localvar_changed
14:13:06:25 <-- [1] weechat obj: 243/380 bytes (37%, 0.06ms), id: _buffer_localvar_changed
```

**Comment by oakkitten** [comment]
thanks for the detailed report! please also provide the build id from Settings → About and the exact WeeChat version (`/v`)

the piece of code that crashes:

    // nicklist
    // _nicklist
    // _nicklist_diff
    @WorkerThread @Override @Cat public void handleMessage(RelayObject obj, String id) {
        ...
        boolean away = entry.getItem("color").asString().contains("weechat.color.nicklist_away");

it is clear that `asString()` returns `null` while it probably shouldn't? or maybe it should?

before fixing this, i'd like to be able to reproduce the issue. do you use weechat in any irregular way? do you have any groups in the nicklist? do you use something that affects nickname colors?

**Comment by killerrabbit** [comment]
Build ID: v0.13-0-gdeca889

I use a tox-weechat plugin located here: https://github.com/haavard/tox-weechat
That plugin does not color nicks in the nicklist, so I suspect that might be the source.

**Comment by oakkitten** [comment]
aha thanks i could reproduce it

**Comment by oakkitten** [comment]
please try the nightly build to see if it works for you (note that automatic playstore publishing is currently broken)
