### ISSUE TITLE
SSH tunnel connection doesn't work (connection reset)

### ISSUE THREAD

**Issue by liskin** [ubergeek42/weechat-android#433]
I tried using the nightly today (weechat-master-8d12b9f.apk) and connecting through SSH tunnel doesn't seem to work any more. WeeChat says "connection closed by peer" and tcpdump seems to confirm that:

```
# tcpdump -n -i lo -s 0 port 12001
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on lo, link-type EN10MB (Ethernet), capture size 262144 bytes
16:17:51.070342 IP 127.0.0.1.56754 > 127.0.0.1.12001: Flags [S], seq 1102476922, win 43690, options [mss 65495,nop,nop,TS val 2905247712 ecr 0,nop,wscale 7], length 0
16:17:51.070356 IP 127.0.0.1.12001 > 127.0.0.1.56754: Flags [S.], seq 2401217504, ack 1102476923, win 43690, options [mss 65495,nop,nop,TS val 2905247712 ecr 2905247712,nop,wscale 7], length 0
16:17:51.070368 IP 127.0.0.1.56754 > 127.0.0.1.12001: Flags [.], ack 1, win 342, options [nop,nop,TS val 2905247712 ecr 2905247712], length 0
16:17:51.074480 IP 127.0.0.1.56754 > 127.0.0.1.12001: Flags [F.], seq 1, ack 1, win 342, options [nop,nop,TS val 2905247716 ecr 2905247712], length 0
16:17:51.078194 IP 127.0.0.1.12001 > 127.0.0.1.56754: Flags [.], ack 2, win 342, options [nop,nop,TS val 2905247720 ecr 2905247716], length 0
16:17:51.099576 IP 127.0.0.1.12001 > 127.0.0.1.56754: Flags [F.], seq 1, ack 2, win 342, options [nop,nop,TS val 2905247741 ecr 2905247716], length 0
16:17:51.099594 IP 127.0.0.1.56754 > 127.0.0.1.12001: Flags [.], ack 2, win 342, options [nop,nop,TS val 2905247741 ecr 2905247741], length 0
```

Note that all packets are `length 0`, so no data is exchanged whatsoever, and note that it is the weechat-android side that sends FIN first. To confirm that this is indeed the case, I tcpdumped the ssh connection as well (which I won't paste here not to reveal my addresses) and there it is again the weechat-android who sends FIN first.

This works in the prod version from Google Play (0.13 from October 7, 2018) just fine.

I tried adb logcat, which is full of noise but this bit stands out:

```
03-18 16:08:34.680  1149  8043 E 🐶    : com.ubergeek42.weechat.relay.connection.Utils$StreamClosed: Stream unexpectedly closed
03-18 16:08:34.680  1149  8043 E 🐶    :        at com.ubergeek42.weechat.relay.connection.RelayConnection.lambda$startThreadsAndAuthenticate$4$RelayConnection(RelayConnection.java:2)
03-18 16:08:34.680  1149  8043 E 🐶    :        at com.ubergeek42.weechat.relay.connection.-$$Lambda$RelayConnection$j43tQCdCxT45afqOcBqFbOhYSNo.run(Unknown Source:2)
03-18 16:08:34.680  1149  8043 E 🐶    :        at com.ubergeek42.weechat.relay.connection.RelayConnection$Protected.run(RelayConnection.java:1)
03-18 16:08:34.680  1149  8043 E 🐶    :        at com.ubergeek42.weechat.relay.connection.Utils$FriendlyThread.run(Utils.java:1)
```

Is there anything else I can try?

**Comment by oakkitten** [comment]
thanks for the detailed report! i think i managed to reproduce the issue. the problem seems to be in the proguard optimizations; i'll try to nail it down

**Comment by oakkitten** [comment]
please try bf0cb51 ([apk via http](http://weechat-android.ubergeek42.com/weechat-issue/433-bf0cb51.apk)) to see if it works for you

**Comment by liskin** [comment]
@oakkitten It works!

**Comment by liskin** [comment]
Thanks! ♥
