### ISSUE TITLE
Connection refused seemingly without any reason after upgrade to 0.14 with SSH tunnel option

### ISSUE THREAD

**Issue by Porkepix** [ubergeek42/weechat-android#436]
After years using `weechat-android` without serious issues, I got on F-droid the `0.14` upgrade today and installed it.
It broke the connection to my server, while I didn't touch any setting.
Setup is relay on standard port and connection through SSH tunnel.
Here's the corresponding `adb logcat -v threadtime`:

```
03-23 21:37:24.539 25745 26509 I 🐶    : c-4  : Jsch Connecting to [MY_IP] port 22
03-23 21:37:24.591 25745 26509 I 🐶    : c-4  : Jsch Connection established
03-23 21:37:24.666 25745 26509 I 🐶    : c-4  : Jsch Remote version string: SSH-2.0-OpenSSH_8.2
03-23 21:37:24.666 25745 26509 I 🐶    : c-4  : Jsch Local version string: SSH-2.0-JSCH-0.1.54
03-23 21:37:24.667 25745 26509 I 🐶    : c-4  : Jsch CheckCiphers: aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,3des-ctr,arcfour,arcfour128,arcfour256
03-23 21:37:24.678 25745 26509 I 🐶    : c-4  : Jsch CheckKexes: diffie-hellman-group14-sha1,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521
03-23 21:37:24.831 25745 26509 I 🐶    : c-4  : Jsch CheckSignatures: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
03-23 21:37:24.837 25745 26509 I 🐶    : c-4  : Jsch SSH_MSG_KEXINIT sent
03-23 21:37:24.837 25745 26509 I 🐶    : c-4  : Jsch SSH_MSG_KEXINIT received
03-23 21:37:24.838 25745 26509 I 🐶    : c-4  : Jsch kex: server: curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256
03-23 21:37:24.838 25745 26509 I 🐶    : c-4  : Jsch kex: server: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256
03-23 21:37:24.838 25745 26509 I 🐶    : c-4  : Jsch kex: server: chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
03-23 21:37:24.840 25745 26509 I 🐶    : c-4  : Jsch kex: server: chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
03-23 21:37:24.842 25745 26509 I 🐶    : c-4  : Jsch kex: server: hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com
03-23 21:37:24.843 25745 26509 I 🐶    : c-4  : Jsch kex: server: hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com
03-23 21:37:24.843 25745 26509 I 🐶    : c-4  : Jsch kex: server: none,zlib@openssh.com
03-23 21:37:24.843 25745 26509 I 🐶    : c-4  : Jsch kex: server: none,zlib@openssh.com
03-23 21:37:24.844 25745 26509 I 🐶    : c-4  : Jsch kex: server:
03-23 21:37:24.844 25745 26509 I 🐶    : c-4  : Jsch kex: server:
03-23 21:37:24.845 25745 26509 I 🐶    : c-4  : Jsch kex: client: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
03-23 21:37:24.846 25745 26509 I 🐶    : c-4  : Jsch kex: client: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
03-23 21:37:24.846 25745 26509 I 🐶    : c-4  : Jsch kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc
03-23 21:37:24.846 25745 26509 I 🐶    : c-4  : Jsch kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc
03-23 21:37:24.846 25745 26509 I 🐶    : c-4  : Jsch kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
03-23 21:37:24.846 25745 26509 I 🐶    : c-4  : Jsch kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
03-23 21:37:24.846 25745 26509 I 🐶    : c-4  : Jsch kex: client: none
03-23 21:37:24.846 25745 26509 I 🐶    : c-4  : Jsch kex: client: none
03-23 21:37:24.846 25745 26509 I 🐶    : c-4  : Jsch kex: client:
03-23 21:37:24.846 25745 26509 I 🐶    : c-4  : Jsch kex: client:
03-23 21:37:24.847 25745 26509 I 🐶    : c-4  : Jsch kex: server->client aes128-ctr hmac-sha2-256 none
03-23 21:37:24.847 25745 26509 I 🐶    : c-4  : Jsch kex: client->server aes128-ctr hmac-sha2-256 none
03-23 21:37:24.931 25745 26509 I 🐶    : c-4  : Jsch SSH_MSG_KEX_DH_GEX_REQUEST(1024<2048<2048) sent
03-23 21:37:24.931 25745 26509 I 🐶    : c-4  : Jsch expecting SSH_MSG_KEX_DH_GEX_GROUP
03-23 21:37:25.106 25745 26509 I 🐶    : c-4  : Jsch SSH_MSG_KEX_DH_GEX_INIT sent
03-23 21:37:25.106 25745 26509 I 🐶    : c-4  : Jsch expecting SSH_MSG_KEX_DH_GEX_REPLY
03-23 21:37:25.319 25745 26509 I 🐶    : c-4  : Jsch ssh_rsa_verify: signature true
03-23 21:37:25.320 25745 26509 I 🐶    : c-4  : Jsch Host '[MY_IP]' is known and matches the RSA host key
03-23 21:37:25.320 25745 26509 I 🐶    : c-4  : Jsch SSH_MSG_NEWKEYS sent
03-23 21:37:25.320 25745 26509 I 🐶    : c-4  : Jsch SSH_MSG_NEWKEYS received
03-23 21:37:25.322 25745 26509 I 🐶    : c-4  : Jsch SSH_MSG_SERVICE_REQUEST sent
03-23 21:37:25.346 25745 26509 I 🐶    : c-4  : Jsch SSH_MSG_SERVICE_ACCEPT received
03-23 21:37:25.397 25745 26509 I 🐶    : c-4  : Jsch Authentications that can continue: password,publickey
03-23 21:37:25.397 25745 26509 I 🐶    : c-4  : Jsch Next authentication method: password
03-23 21:37:25.617 25745 26509 I 🐶    : c-4  : Jsch Authentication succeeded (password).
03-23 21:37:25.646 25745 26514 E 🐶    : r-4  : RelayConnection readStream: exception while state == CONNECTED
03-23 21:37:25.646 25745 26514 E 🐶    : java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
03-23 21:37:25.646 25745 26514 E 🐶    : 	at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:588)
03-23 21:37:25.646 25745 26514 E 🐶    : 	at libcore.io.IoBridge.recvfrom(IoBridge.java:552)
03-23 21:37:25.646 25745 26514 E 🐶    : 	at java.net.PlainSocketImpl.read(PlainSocketImpl.java:481)
03-23 21:37:25.646 25745 26514 E 🐶    : 	at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
03-23 21:37:25.646 25745 26514 E 🐶    : 	at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
03-23 21:37:25.646 25745 26514 E 🐶    : 	at android.support.v4.media.MediaDescriptionCompatApi21$Builder.readAll(MediaDescriptionCompatApi21.java:2)
03-23 21:37:25.646 25745 26514 E 🐶    : 	at com.ubergeek42.weechat.relay.connection.RelayConnection.lambda$startThreadsAndAuthenticate$4$RelayConnection(RelayConnection.java:2)
03-23 21:37:25.646 25745 26514 E 🐶    : 	at com.ubergeek42.weechat.relay.connection.-$$Lambda$RelayConnection$j43tQCdCxT45afqOcBqFbOhYSNo.run(lambda)
03-23 21:37:25.646 25745 26514 E 🐶    : 	at com.ubergeek42.weechat.relay.connection.RelayConnection$Protected.run(RelayConnection.java:1)
03-23 21:37:25.646 25745 26514 E 🐶    : 	at com.ubergeek42.weechat.relay.connection.Utils$FriendlyThread.run(Utils.java:1)
03-23 21:37:25.646 25745 26514 E 🐶    : Caused by: android.system.ErrnoException: recvfrom failed: ECONNRESET (Connection reset by peer)
03-23 21:37:25.646 25745 26514 E 🐶    : 	at libcore.io.Posix.recvfromBytes(Native Method)
03-23 21:37:25.646 25745 26514 E 🐶    : 	at libcore.io.Posix.recvfrom(Posix.java:189)
03-23 21:37:25.646 25745 26514 E 🐶    : 	at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)
03-23 21:37:25.646 25745 26514 E 🐶    : 	at libcore.io.IoBridge.recvfrom(IoBridge.java:549)
03-23 21:37:25.646 25745 26514 E 🐶    : 	... 8 more
03-23 21:37:25.647 25745 26508 E RelayService: → onException("SocketException")
03-23 21:37:25.649 25745 26509 I 🐶    : c-4  : Jsch Disconnecting from [MY_IP] port 22
03-23 21:37:25.652 25745 26512 I 🐶    : Conn : Jsch Caught an exception, leaving main loop due to Socket closed
```

Just in case settings format changed, I did set again the SSH config, without any success as expected.

EDIT: Environment is Android Marshmallow (6.0.1) with stock rom on a Xperia Z3 compact.

**Comment by megumintyan** [comment]
Same.
```
relay: reading data on socket for client 1/weechat/::1: error 2 (connection closed by peer)
relay: disconnected from client 1/weechat/::1
```

**Comment by oakkitten** [comment]
this has been fixed in master and a new version should arrive soon to F-Droid

**Comment by minus7** [comment]
Duplicate of #433 
Fix in https://github.com/ubergeek42/weechat-android/commit/bf0cb5159e50ab6a15ea61bea3438c2f50069a6e

**Comment by tagru** [comment]
> 
> 
> this has been fixed in master and a new version should arrive soon to F-Droid

Can you elaborate when this might happen?

**Comment by Porkepix** [comment]
> > this has been fixed in master and a new version should arrive soon to F-Droid
> 
> Can you elaborate when this might happen?

It happened this morning :)
Closing the issue!
