### ISSUE TITLE
Can't load private SSH key: Invalid structure

### ISSUE THREAD

**Issue by minus7** [ubergeek42/weechat-android#468]
The 1.1 release somehow removed my configured SSH key and when i try to re-add it I get an error with the following stack trace from logcat:

```
E FilePreference: error
E FilePreference: java.io.IOException: Invalid PEM structure, '-----BEGIN...' missing
E FilePreference: 	at com.ubergeek42.weechat.relay.connection.SSHConnection.makeKeyPair(SSHConnection.java:213)
E FilePreference: 	at androidx.preference.PrivateKeyPickerPreference.saveData(PrivateKeyPickerPreference.java:2)
E FilePreference: 	at androidx.preference.PasswordedFilePickerPreference.saveData(PasswordedFilePickerPreference.java:2)
E FilePreference: 	at androidx.preference.FilePreference.saveDataAndShowToast(FilePreference.java:2)
E FilePreference: 	at com.ubergeek42.WeechatAndroid.PreferencesActivity$PreferencesFragment.onActivityResult(PreferencesActivity.java:6)
E FilePreference: 	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:8)
E FilePreference: 	at android.app.Activity.dispatchActivityResult(Activity.java:6937)
E FilePreference: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4122)
E FilePreference: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4169)
E FilePreference: 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
E FilePreference: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1552)
E FilePreference: 	at android.os.Handler.dispatchMessage(Handler.java:102)
E FilePreference: 	at android.os.Looper.loop(Looper.java:154)
E FilePreference: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
E FilePreference: 	at java.lang.reflect.Method.invoke(Native Method)
E FilePreference: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
E FilePreference: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

The file itself does look valid; it's the identical file I've used before.
Oddly enough, SSHConnection.java at revision 063326ec6971da0de8bc347bf7a6373ed0b9e505 only has 163 lines

**Comment by minus7** [comment]
Looks like the SSH lib doesn't support the key format I use anymore: `-----BEGIN PRIVATE KEY-----`

**Comment by oakkitten** [comment]
this sounds like the PKCS8 format. can be generated using `$ ssh-keygen -m pkcs8 -f file`. might be wise to ask the library to support that
