### ISSUE TITLE
F-Droid build broken (cats should only work in debug mode)

### ISSUE THREAD

**Issue by jspricke** [ubergeek42/weechat-android#478]
Got this with the new 1.3 build on F-Droid:
```
11-23 09:50:34.907  3959  3959 D AndroidRuntime: Shutting down VM
11-23 09:50:34.908  3959  3959 E AndroidRuntime: FATAL EXCEPTION: main
11-23 09:50:34.908  3959  3959 E AndroidRuntime: Process: com.ubergeek42.WeechatAndroid, PID: 3959
11-23 09:50:34.908  3959  3959 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.ubergeek42.WeechatAndroid.Weechat: java.lang.RuntimeException: cats should only work in debug mode
11-23 09:50:34.908  3959  3959 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6465)
11-23 09:50:34.908  3959  3959 E AndroidRuntime:        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
11-23 09:50:34.908  3959  3959 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
11-23 09:50:34.908  3959  3959 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
11-23 09:50:34.908  3959  3959 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
11-23 09:50:34.908  3959  3959 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)
11-23 09:50:34.908  3959  3959 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-23 09:50:34.908  3959  3959 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
11-23 09:50:34.908  3959  3959 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
11-23 09:50:34.908  3959  3959 E AndroidRuntime: Caused by: java.lang.RuntimeException: cats should only work in debug mode
11-23 09:50:34.908  3959  3959 E AndroidRuntime:        at com.ubergeek42.cats.Cats.setup(Cats.java:23)
11-23 09:50:34.908  3959  3959 E AndroidRuntime:        at com.ubergeek42.WeechatAndroid.Weechat.onCreate(Weechat.java:34)
11-23 09:50:34.908  3959  3959 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189)
11-23 09:50:34.908  3959  3959 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
11-23 09:50:34.908  3959  3959 E AndroidRuntime:        ... 8 more
11-23 09:50:34.912  4855 18285 W ActivityTaskManager:   Force finishing activity com.ubergeek42.WeechatAndroid/.WeechatActivity
```

(Can have a look later, currently at work.)

**Comment by jamestomasino** [comment]
Also an issue here. I downgraded to 1.2 for now and things are fine again

**Comment by oakkitten** [comment]
sorry, my bad. there was a big refactor of build scripts and i removed the release configuration as it's not used for playstore... i didn't realize that f-droid uses it

funny that f-droid managed to make a build at all with missing configuration

hopefully 5427104502b632ee5207aa200811a5b49e16971e will resolve this

**Comment by yan12125** [comment]
Got the same issue, and I asked F-Droid devs for another update https://gitlab.com/fdroid/fdroiddata/-/issues/2224

**Comment by quite** [comment]
@yan12125  i think their build server runs basically all the time. The cycles are rather long, from detecting new version, to published. And there at least used to be many failures. It's ready when it is ready :)

**Comment by yan12125** [comment]
Version 1.3.1 is uploaded to F-Droid mirrors! It looks good.

> It's ready when it is ready :)

Hopefully my ticket makes it slightly faster :) I remember the last time another F-Droid app was broken, a new version took more than a week to arrive F-Droid mirrors.

**Comment by quite** [comment]
1.3.1 works for me

**Comment by jspricke** [comment]
1.3.1 is now the recommend and working version on F-Droid.
